### ISSUE TITLE
出典の表記

### ISSUE THREAD

**Issue by tosseto** [HeRoMo/address2geocode#1]
Read Meのところにできれば、下記の事項にもとづき出典等書いていただけるとありがたいです！
http://newspat.csis.u-tokyo.ac.jp/geocode/modules/geocode/index.php?content_id=2

**Comment by HeRoMo** [comment]
ご指摘ありがとうございます。
ご指摘は示されたURLの「第4条 利用の明記」に従った表示を、とのことだと理解しました。

スプレッドシートのアドオンは仕組み的にはWebアプリケーションだと思うのですが、ユーザによるインストール作業が必要なため、「第4条 利用の明記」によると(3)と(4)の中間くらいかと思います。
したがって、利用API としてREADMEにもアドオンで表示するUIにも以下の様に記載したのですが、これ以外に追加すべき表示があるということでしょうか？

> このアドオンは緯度経度への変換は次のWebAPIを利用しています。
> - [CSISシンプルジオコーディング実験](http://newspat.csis.u-tokyo.ac.jp/geocode/modules/geocode/index.php?content_id=1) ([街区レベル位置参照情報](http://nlftp.mlit.go.jp/isj/)) API

**Comment by HeRoMo** [comment]
現在の表記でOKということなのでクローズします。
